### PR TITLE
Processing six-month historical datasets from the EIA GridMonitor

### PR DESCRIPTION
**Pull request by jdechalendar**
## Commit summary
```
commit a3cc178d943de610aed76ea99596ade469fa9288
Date:   Sun Dec 31 19:10:15 2023 +0100

    Process six-month files from EIA Grid Monitor

    * Download script

    * Parsers for six month bulk files - Implemented in eia_bulk_grid_monitor.py

    * Script to parse/process EIA Grid Monitor in bulk

    * bugfix(bulk_process): concat should use axis=1

    * Moved EIA_Grid_Monitor downloads to a downloads folder

    * Updates to Makefile and requirements in setup.py

    * Added notebook to demo usage of bulk data downloads

    * Update to viz.reports to use GraphData

    * update README

commit 3e26cbc21ab2d1d99e18a8b88c1bbb94a2079fd8
Author: Jacques de Chalendar <jdechalendar@stanford.edu>
Date:   Mon Jan 1 11:41:48 2024 +0100

    workflows.make_dataset minor updates

    * Signature change: start and end are now optional

    * Docstring update

```

## Sample output from [sanity check notebook](https://github.com/jdechalendar/gridemissions/blob/bulk/notebooks/Bulk%20Data%20Demo.ipynb)

image

image

image

image

image

image

image

### CODE REVIEW

**Comment by jdechalendar** [comment]
@ktehranchi @JuliaF556 I think this is almost ready to be closed. Bulk dataset is available [here](https://gridemissions.s3.us-east-2.amazonaws.com/processed.tar.gz). I also added [this notebook](https://github.com/jdechalendar/gridemissions/blob/bulk/notebooks/Bulk%20Data%20Demo.ipynb) on this branch with my quick sanity check.

Could you both try using these updated datasets for your respective projects. If the data seem to be what you expect I will close this PR. I am keeping track of unfinished work I still want to do for this in #22

**Comment by JuliaF556** [comment]
The bulk download works for me, so I'm just struggling with the new EIA format and will build a work-around to construct a full timeseries based on the old format for my project.

**Comment by ktehranchi** [comment]
Data looks good on my end. Will you be keeping this format of the data? ie separated into the equivalent 6 mo files?

**Comment by jdechalendar** [comment]
> Data looks good on my end. Will you be keeping this format of the data? ie separated into the equivalent 6 mo files?

Planning on also merging into one file with everything -- but haven't gotten around to doing that yet.

**Comment by JuliaF556** [comment]
I built a [workaround](https://github.com/jdechalendar/julia-msthesis/commit/bee21744cd52be0937a09c21a4edb358f5551424) to append the new 6-month data to my stored dataset (2015-February 2023). It might be helpful, but I'm keeping everything in the old naming format. I'm also dropping columns that weren't reported in EIA930 before the naming change.

**Comment by ktehranchi** [comment]
Screenshot 2024-04-09 at 3 49 44 PM
Hey Jacques - I just noticed the minimum of all the energy carriers was ~1.0.... Is there a reason why? Should I subtract 1 from all the data?

**Comment by grgmiller** [comment]
See: https://github.com/singularity-energy/open-grid-emissions/issues/113

I think this is a placeholder for missing data

**Pull request merged**
